#!/bin/sh
# scripts/entrypoint-local.sh
# Fixes permissions (Windows Docker Desktop presents bind-mounts as 777,
# FreeRADIUS refuses world-writable config) then generates a local.conf
# with real connection values substituted from environment variables,
# then generates clients.conf with resolved secrets (FreeRADIUS does not
# expand ${var} in the clients file secret field),
# then hands off to the real image entrypoint.

set -e

echo "[local] fixing config file permissions..."
find /etc/freeradius -type f -exec chown root:freerad {} \; -exec chmod 640 {} \; 2>/dev/null || true
find /etc/freeradius -type d -exec chown root:freerad {} \; -exec chmod 750 {} \; 2>/dev/null || true

echo "[local] writing local.conf with resolved env vars..."
cat > /etc/freeradius/local.conf << EOF
# Generated by entrypoint-local.sh — do not edit manually.
# Contains connection parameters resolved from Docker environment variables.

# SQL connection — used by mods-enabled/sql via \$INCLUDE
sql_server   = "${DB_HOST:-pgbouncer}"
sql_port     = "${DB_PORT:-5432}"
sql_login    = "${DB_USER:-radius}"
sql_password = "${DB_PASS:-localpass}"
sql_db       = "${DB_NAME:-radius}"

# Thread pool
radius_workers = "${RADIUS_WORKERS:-4}"

# Shared secrets — used by clients.conf
radius_secret        = "${RADIUS_SECRET:-localtesting}"
radius_health_secret = "${RADIUS_HEALTH_SECRET:-CHANGE_ME_health_secret}"
radius_net_subnet    = "${RADIUS_NET_SUBNET:-172.29.0.0/16}"

# Redis (cache profile)
redis_host     = "${REDIS_HOST:-redis}"
redis_port     = "${REDIS_PORT:-6379}"
redis_password = "${REDIS_PASSWORD:-localredis}"
cache_ttl      = "${RADIUS_CACHE_TTL:-300}"
EOF
chmod 640 /etc/freeradius/local.conf
chown root:freerad /etc/freeradius/local.conf

echo "[local] writing clients.conf with resolved secrets..."
cat > /etc/freeradius/clients.conf << EOF
# Generated by entrypoint-local.sh — do not edit manually.
# FreeRADIUS does not expand \${var} in the secret field of clients.conf,
# so secrets are substituted directly by the entrypoint script.
#
# require_message_authenticator = true is set on all clients.
# This is required by FreeRADIUS 3.2.7+ as a mitigation for
# CVE-2024-3596 (BlastRADIUS). Without it, FreeRADIUS warns and
# refuses to process auth requests from clients that send
# Message-Authenticator in their packets — which radtest always does.

# Loopback — healthcheck
client localhost {
    ipaddr                        = 127.0.0.1
    secret                        = ${RADIUS_HEALTH_SECRET:-CHANGE_ME_health_secret}
    shortname                     = localhost
    nas_type                      = other
    require_message_authenticator = true
}

# Docker bridge — testing container and load generator
client docker_internal {
    ipaddr                        = ${RADIUS_NET_SUBNET:-172.29.0.0/16}
    secret                        = ${RADIUS_SECRET:-localtesting}
    shortname                     = docker_internal
    nas_type                      = other
    require_message_authenticator = true
}

EOF
chmod 640 /etc/freeradius/clients.conf
chown root:freerad /etc/freeradius/clients.conf

echo "[local] handing off to freeradius entrypoint..."
exec /docker-entrypoint.sh "$@"